---
- name: "security | Configure security on cluster nodes"
  ansible.builtin.include_tasks: security.yml
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['architecture'] == "aarch64"
    - "'node' in inventory_hostname"

- name: "security | Install packages"
  ansible.builtin.include_tasks: packages-debian.yml
  when:
    - ansible_facts['distribution'] == "Debian"

- name: "security | Ensure group {{sec_group}} exists with correct gid {{sec_gid}}"
  ansible.builtin.group:
    name: "{{ sec_group }}"
    state: present
    gid: "{{ sec_gid }}"

- name: "security | Add the user 'security' with a specific uid and a primary group of {{sec_group}}"
  ansible.builtin.user:
    name: "{{ sec_user }}"
    comment: watching you so behave
    uid: "{{ sec_uid }}"
    group: "{{ sec_group }}"
    gid: "{{sec_gid}}"

- name: "security | setup lynis"
  ansible.builtin.include_tasks: lynis.yml
  when:
    - ansible_facts['distribution'] == "Debian"
