---
- name: "Install Security Packages"
  apt:
    package: [
      "lynis",
      "pass",
      "tiger",
      "gnupg2",
      "wipe",
      "keyringer",
      "chkrootkit"
    ]
    state: latest
  tags: admin

- name: "security | Copy security_scan.sh script"
  ansible.builtin.template:
    src: security_scan.sh.j2
    owner: "{{sec_user}}"
    group: "{{sec_group}}"
    dest: "{{bin_dir}}/security_scan.sh"
    mode: 0755

- name: "security | Security scan script add to crontab"
  ansible.builtin.cron:
    name: "lynis scan"
    minute: "13"
    hour: "4"
    job: "{{bin_dir}}/security_scan.sh"

- name: "security | Copy gnupg_check.sh script"
  ansible.builtin.template:
    src: gnupg_check.sh
    owner: "{{sec_user}}"
    group: "{{sec_group}}"
    dest: "{{bin_dir}}/gnupg_check.sh"
    mode: 0755
