---
- name: "Install Security Packages"
  apt:
    package: [
      "lynis",
      "pass",
      "tiger",
      "gnupg2",
      "wipe",
      "keyringer",
      "chkrootkit"
    ]
    state: latest
  tags: admin
