---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cluster_node
    hostname: franklin
    image: ubuntu:latest
    # Do note that running containers in privileged mode is considerably less secure.
    privileged: true
provisioner:
  name: ansible
  log: true
  env:
    HOMELAB_MOLECULE_TEST: True
scenario:
  #become: true
  test_sequence:
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    # -idempotence
    # - side_effect
    # - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
lint: |
  # [ -n "$BASH" ] ;then set -e; fi
  export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/..
  yamllint .
  ansible-lint
  flake8
