---
apiVersion: v1
kind: Service
metadata:
  name: franklin-resume-service
spec:
  type: LoadBalancer
  selector:
    app: my-resume
  externalIPs:
  - 10.10.12.0
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
