services:
  mmmbot:
    image: mmmbot
    build:
      context: ..
      dockerfile: container/hanson/Dockerfile
    container_name: hanson
    volumes:
      - ./src/hanson:/workspaces/hanson
  customer-build:
    build:
      context: ..
      dockerfile: container/rhel8/Dockerfile
      args:
        - RHEL_USER=$RHEL_USER
        - RHEL_PASS=$RHEL_PASS
    image: customer-build
    container_name: customer-build
    ports:
      - "5000:5000"
    volumes:
      - ./:/workspaces/customer-build
