[tox]
envlist = py36
skipsdist = True
skip_missing_interpreters = true

[testenv]
setenv = PYTHONPATH = .
whitelist_externals =
    find
    sudo
commands_pre =
    find {toxinidir}/ -type f -not -path '{toxinidir}/.tox/*' -path '*/__pycache__/*' -name '*.py[c|o]' -delete
commands =
  /opt/airflow/bin/coverage run --rcfile={toxinidir}/.coveragerc -m pytest --setup-show \
    --capture=no -v --junit-xml=/tmp/airflow/TEST-unit.xml {toxinidir}/test
  /bin/coverage report --rcfile={toxinidir}/.coveragerc -m --show-missing
