---
- name: "Converge:: test nfs_client from lab.franklin Collection"
  hosts: localhost
  become: true
  gather_facts: true


  pre_tasks:
  - name: update apt cache
    apt:
      update_cache: yes
    when: ansible_os_family == 'Debian'
    changed_when: no

  - name: add ansible user
    ansible.builtin.user:
      name: ansible
      system: true

  - name: create a log directory
    ansible.builtin.file:
      path: /var/log/ansible
      state: directory
      owner: nobody
      group: nobody
      mode: 0755

  tasks:
    - name: "Moelcule:: Testing NFS Client Role"
      ansible.builtin.include_role:
        name: lab.franklin.nfs
        tasks_from: nfs_client.yml