---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server1
    hostname: server1
    # image: python:3.6-stretch
    image: debian:buster
    # Do note that running containers in privileged mode is considerably less secure.
    privileged: true
provisioner:
  name: ansible
  log: true
  env:
    HOMELAB_MOLECULE_TEST: True
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
lint: |
  set -e
  export ANSIBLE_ROLES_PATH="${MOLECULE_PROJECT_DIRECTORY}/.."
  yamllint .
  ansible-lint
