name: GNU autotools
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux:
    name: GNU Autotools testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make automake autoconf
          version: 1.0

      - name: bootstrap
        run: ${GITHUB_WORKSPACE}/bootstrap.sh
      - name: make test
        run: make test
      - name: make test
        run: make security
      - name: make test
        run: make python