name: Docker Image CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build the docker-compose stack
        run: |
          sudo apt -y install python3-setuptools git
          docker-compose -f docker-compose.yml up -d --build franklin_resume
