name: Script Validation
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux:
    name: LINUX shell script testing
    env:
      PASS: ${{ secrets.PASS }}
      PAN_IP: '34.134.31.136'
    runs-on: ubuntu-latest

    steps:

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-utils pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          version: 1.0

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          PASS: ${{env.PASS }}
          PAN_IP: ${{env.PAN_IP }}

      - name: Setup dev env
        run:  |
          ${GITHUB_WORKSPACE}/bootstrap.sh
          sudo apt update
          make test

      - name: Test generate_docs.sh
        run:  ${GITHUB_WORKSPACE}/bin/generate_docs.sh

      - name: Test stage_release.sh
        run:  ${GITHUB_WORKSPACE}/bin/stage_release.sh -h
