name: build cloudbot pod
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build Cloudbot pod
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build -t gcr.io/gcp-gcs-pso/build-pod:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'gcr.io/gcp-gcs-pso/build-pod:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
