sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
addons:
  apt:
    packages:
    - curl
    - libxml2-utils
    - pandoc
    - aspell
    - aspell-en
install: 
  - python3 -m pip install tox
before_script:
  - sudo apt-get update -qq
script:
- curl https://raw.githubusercontent.com/mike42/mdcheckr/master/mdcheckr -o mdcheckr
- chmod +x mdcheckr
- sudo cp mdcheckr /usr/local/bin
- /usr/local/bin/mdcheckr markdown/pageone.md
- make html
- make doc
- tox 
- coveralls
notifications:
  email: false
