# SPDX-FileCopyrightText: © 2022-2024 DE:AD:10:C5 <franklin@dead10c5.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
CgroupMountpoint="/sys/fs/cgroup"
CgroupAutomount=yes
#CgroupReleaseAgentDir="/etc/slurm-llnl/cgroup"
ConstrainCores=no
#TaskAffinity=no
ConstrainRAMSpace=yes
ConstrainSwapSpace=no
ConstrainDevices=no
AllowedRamSpace=100
AllowedSwapSpace=0
MaxRAMPercent=100
MaxSwapPercent=100
MinRAMSpace=30
