---
- name: "Install isc-dhcp-server on raspbian"
  ansible.builtin.include_tasks: debian.yml
  #when: ansible_os_family == "Debian"
  when:
    - "'server1' in inventory_hostname"

#- include: redhat.yml
#  when: ansible_os_family == "RedHat"

# - name: "Include config.yml"
#   ansible.builtin.include: config.yml
#   when:
#     - "'server1' in inventory_hostname"
#     #- isc_dhcp_config_dhcp

- name: "Copy /etc/dhcpd.conf on server1"
  ansible.builtin.copy:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644
  when:
    - "'server1' in inventory_hostname"
    - HOMELAB_MOLECULE_TEST is not defined

- name: "Copy /etc/dhcpd6.conf on server1"
  ansible.builtin.copy:
    src: dhcpd6.conf
    dest: /etc/dhcp/dhcpd6.conf
    mode: 0644
  when:
    - "'server1' in inventory_hostname"
    - HOMELAB_MOLECULE_TEST is not defined
