---
# use this one to write config and log files to bucket? 
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: upload-configmap-file-to-gcs
  namespace: tekton-pipelines
spec:
  taskRef:
    name: gcs-upload
  workspaces:
  - name: output
    secret:
      secretName: tekton-storage
      defaultMode: 0755
  - name: source
    configMap:
      name: config-artifact-bucket
