---
# this should match what's in the ssl vars, move to top level soon
my_crt: /etc/ssl/certs/server.crt

# the bin dir is on the SSD to reduce wear on the CF cards
bin_dir: /mnt/clusterfs/bin

ansible_email: ©2023-2025 franklin <smoooth.y62wj@passmail.net>
ansible_license: MIT
ansible_managed: MANAGED BY ANSIBLE