---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
lint: |
  [ -n "$BASH" ] ;then set -e; fi
  export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/..
  yamllint .
  ansible-lint
  flake8
