---
- name: "common | Detect OS"
  ansible.builtin.include_tasks: detect_os.yml

- name: "common | Install packages"
  ansible.builtin.include_tasks: packages.yml

#- name: 'Install glances monitoring'
#  ansible.builtin.include: glances.yml

# - name: "common | Copy update_motd.sh script"
#   ansible.builtin.copy:
#     src: "update_motd.sh"
#     dest: "{{sbindir}}/update_motd.sh"
#     mode: 0700

# - name: "common | Remove file ({{bindir}}/update_motd.sh)"
#   ansible.builtin.file:
#     path: "{{bindir}}/update_motd.sh"
#     state: absent

- name: "common | Remove file ({{bindir}}/bootstrap.sh)"
  ansible.builtin.file:
    path: "{{bindir}}/bootstrap.sh"
    state: absent

# There is only one bootstrap.sh now, not a version for each OS/arch
# - name: "common | Copy bootstrap.sh"
#   ansible.builtin.copy:
#     src: bootstrap.sh
#     owner: root
#     dest: "{{sbindir}}/bootstrap.sh"
#     mode: 0744