---
- name: "common | Detect OS"
  ansible.builtin.include_tasks: detect_os.yml

- name: "common | Install packages"
  ansible.builtin.include_tasks: packages.yml

#- name: 'Install glances monitoring'
#  ansible.builtin.include: glances.yml

- name: "common | Copy update_motd.sh script"
  ansible.builtin.copy:
    src: "update_motd.sh"
    dest: /usr/local/bin/update_motd.sh
    mode: 0755

# There is only one bootstrap.sh now, not a version for each OS/arch
- name: "common | Copy bootstrap.sh"
  ansible.builtin.copy:
    src: bootstrap.sh
    owner: "root"
    dest: /usr/local/sbin/bootstrap.sh
    mode: 0744
