---
- name: "install nvidia packages"
  apt:
    name:
      - tigervnc-standalone-server
      - neofetch
      - python3-pip
      - virtualenv
      - synaptic
      - apt-utils
      - libhdf5-serial-dev
      - hdf5-tools
      - libhdf5-dev
      - zlib1g-dev
      - zip
      - libjpeg8-dev
      - liblapack-dev
      - libblas-dev
      - python3-pip
      - gfortran
    force_apt_get: true
    update_cache: true
  tags:
    - cluster
    - nvidia

- name: "Remove unneeded packages"
  apt:
    package: [
      "libreoffice",
    ]
    state: absent
  tags:
    - cluster
    - nvidia
