---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: molecule-ubuntu
    image: ubuntu:20.04
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
driver:
  name: podman
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
provisioner:
  name: ansible
  env:
    HOMELAB_MOLECULE_TEST: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
