kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: ctfd
  name: regionalpd-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
      - us-central1-a
      - us-central1-b
      - us-central1-c
