---
- name: 'Install Kerberos Client Packages on Debian/Ubuntu'
  ansible.builtin.apt:
    package: [
      'sshpass',
      'krb5-user',
      'krb5-config',
      'libpam-krb5',
      'libpam-ccreds',
      'nss-updatedb'
      ]
    state: latest
  tags: admin
  when:
    - ansible_facts['distribution'] == "Debian" 
    #- ansible_distribution == 'Ubuntu'

