---
- name: 'kerberos | Install Kerberos Client Packages on Debian/Ubuntu'
  ansible.builtin.apt:
    package: [
      'sshpass',
      'krb5-user',
      'krb5-config',
      'libpam-krb5',
      'libpam-ccreds',
      'nss-updatedb',
      'kstart',
      'ksshaskpass'
      ]
    state: latest
  tags:
    - krb5
    - debian
  when:
    - ansible_facts['distribution'] == "Debian"
