---
- name: "Install Kerberos server packages"
  ansible.builtin.include_tasks: kerberos_server_packages.yml
  when:
    - "'server2' in ansible_hostname"
    - "'odroid-c1' in ansible_hostname"

- name: "Install kerberos server setup"
  ansible.builtin.include_tasks: kerberos_server.yml
  when:
    - "'server2' in ansible_hostname"
    - "'odroid-c1' in ansible_hostname"

- name: "Install Kerberos client packages"
  ansible.builtin.include_tasks: kerberos_client_packages.yml

- name: "Init Kerberos client"
  ansible.builtin.include_tasks: configure.yml

- name: "Configure Kerberos client"
  ansible.builtin.include_tasks: configure.yml

- name: "Install Kerberos Client setup"
  ansible.builtin.include_tasks: kerberos_client.yml
