---
# sudo systemctl disable systemd-resolved
# sudo systemctl stop systemd-resolved

# sudo unlink /etc/resolv.conf

# install new resolv.conf for example
# echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf

# apt install dnsmasq

# copy /etc/dnsmasq.conf

# restart dns masq
