---

# sudo sysctl -a | grep disable_ipv6 | grep "^net."
# ip -6 route


- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  when: ansible_all_ipv6_addresses
