---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-tools
  namespace: cloud-tools
  labels:
    app: cloud-tools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-tools
  template:
    metadata:
      labels:
        app: cloud-tools
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - dev-node 
      containers:
        - name: ct-flask
          image: gcr.io/gcp-gcs-pso/ct-flask:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
#          volumeMounts:
#            - name: nfs-vol
#              mountPath: "/mnt/data"
#     volumes:
#        - name: nfs-vol
#          persistentVolumeClaim:
#            claimName: flask-pvc