---
- name: 'Ansible Playbook for Media hosts'
  hosts: media
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - common
    - ldap
    - kerberos
    - ssh
    - media
    - shell
    - security
