---
- name: 'Ansible Playbook for Nvidia Cluster'
  hosts: nvidia_nodes
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - nfs
    #- common
    - dns
    #- ldap
    #- kerberos
    #- ssh
  environment:
    DEBIAN_FRONTEND: noninteractive
