---
- name: "Ansible Playbook: lab.bitsmasher.net"
  hosts: gpu
  become: true
  gather_facts: true
  
  environment:
    DEBIAN_FRONTEND: noninteractive
  tasks:
    - name: Display all facts
      debug:
        var: ansible_facts
  roles:
    - ntp
