---
- name: 'Ansible Playbook: lab.bitsmasher.net'
  hosts: debian, openbsd, nvidia_nodes, raspi_nodes, raspi_servers, popos
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - common
    - ntp

