---
- name: 'Ansible Playbook for Ubuntu'
  hosts: ubuntu
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - python
    - common
    - dns
    - ldap
    - kerberos
    - ssh
    - nfs
    - shell
    - security
