---
# - name: "auks | install auks dependency packages"
#   ansible.builtin.apt:
#     pkg:
#       - git
#       - flex
#       - bison
#       - byacc
#       - autoconf
#       - automake
#       - zlib1g-dev
#       - libkrb5-dev
#     force_apt_get: true
#     update_cache: true
#   tags:
#     - cluster

# this one uses the file vars/Debian.yml
# - name: "Install auks packages"
#   package:
#     name: "{{ auks__packages_names|list }}"
#     state: present

- name: "auks | install auks dependency packages"
  ansible.builtin.apt:
    pkg:
    name: "{{ auks__packages_names|list }}"
    state: present
    force_apt_get: true
    update_cache: true
  tags:
    - cluster

- name: "auks | check if dir exists"
  ansible.builtin.stat:
    path: "{{auks_build_dir}}"
  register: q

- name: "auks | Clone the auks repo"
  ansible.builtin.git:
    repo: https://github.com/cea-hpc/auks.git
    dest: "{{software_dir}}"
  when:
    - q.stat.isdir is not defined

- name: "auks | autoreconf AUKS"
  ansible.builtin.command: autoreconf -fi
  args:
    chdir: "{{auks_build_dir}}"

- name: "auks | configure AUKS"
  ansible.builtin.command: ./configure
  args:
    chdir: "{{auks_build_dir}}"

- name: "auks | Build the default AUKS target"
  community.general.make:
    chdir: "{{auks_build_dir}}"

- name: "auks | Make install AUKS"
  community.general.make:
    chdir: "{{auks_build_dir}}"
    target: install

- name: "auks | add /usr/local/lib to /etc/ld.so.conf"
  ansible.builtin.lineinfile:
    path: /etc/ld.so.conf
    line: "/usr/local/lib"
