---
- name: "Install MPICH client worker node"
  ansible.builtin.apt:
    package:
      [
        "r-base",
        "openmpi-bin",
        "openmpi-common",
        "libopenmpi3",
        "libopenmpi-dev",
        "mpi-default-dev",
      ]
    state: latest
  tags: cluster
  when: "'head' not in inventory_hostname"


