---
- name: 'Clone the nhc repo'
  ansible.builtin.git:
   repo: https://github.com/mej/nhc.git
   dest: '{{ nhc_build_dir }}'

- name: "autoreconf NHC"
  ansible.builtin.command: autoreconf -fi
  args:
    chdir: '{{ nhc_build_dir }}'

- name: "configure NHC"
  ansible.builtin.command: ./configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/libexec
  args:
    chdir: '{{ nhc_build_dir }}'

- name: "Build the default AUKS target"
  community.general.make:
    chdir: '{{ nhc_build_dir }}'
    target: test

- name: "Make install NHC"
  community.general.make:
    chdir: '{{ nhc_build_dir }}'
    target: install