---
- name: "nhc | check if dir exists"
  ansible.builtin.stat:
    path: "{{nhc_build_dir}}"
  register: p

- name: "nhc | Clone the nhc repo"
  ansible.builtin.git:
    repo: https://github.com/mej/nhc.git
    dest: "{{software_dir}}"
  when:
   - p.stat.isdir is not defined
   - not p.stat.isdir

- name: "nhc | autoreconf NHC"
  ansible.builtin.command: autoreconf -fi
  args:
    chdir: "{{nhc_build_dir}}"

# is there a way to configure the log dir
- name: "nhc | configure NHC"
  #ansible.builtin.command: ./configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/libexec
  args:
    chdir: "{{nhc_build_dir}}"

- name: "nhc | Build NHC"
  ansible.builtin.command: make
  args:
    chdir: "{{nhc_build_dir}}"

# - name: "nhc | Make install NHC"
#   ansible.builtin.command: make install
#   args:
#     chdir: "{{nhc_build_dir}}"

- name: 'nhc | install nhc.conf'
  ansible.builtin.template:
    src: nhc.conf.j2
    dest: "/usr/local/etc/nhc/nhc.conf"
    mode: "0644"
    owner: "{{nhc_user}}"
    group: "{{nhc_group}}"
  tags: cluster
