---
- name: "slurm | Install Slurm scheduler on Raspi Cluster worker node"
  ansible.builtin.apt:
    name:
      - slurmd
      - slurm-client
      - libpmix-dev
    state: latest
    force_apt_get: true
    update_cache: true
  when:
    - "'node' in inventory_hostname"
  tags: cluster

- name: "slurm | install server mpi/slurm dependencies"
  ansible.builtin.apt:
    name:
      - gfortran
      - libpmix-dev
      - slurm-wlm
      - slurmctld
    force_apt_get: true
    update_cache: true
  when:
    - "'head' in inventory_hostname"
  tags: cluster

- name: 'slurm | install slurm.conf'
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: "/etc/slurm/slurm.conf"
    mode: "0644"
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
  tags: cluster

# This is causing the daemon to fail
#- name: 'Set NodeName in /etc/slurm-llnl/slurm.conf'
#  lineinfile:
#    path: /etc/slurm-llnl/slurm.conf
#    regexp: '^NodeName=server'
#    line: "NodeName={{ ansible_hostname }} CPUs=4 State=UNKNOWN"
#  tags: cluster

- name: Change slurm file ownership, group and permissions
  ansible.builtin.file:
    path: "{{slurm_dir}}"
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"

- name: "slurm | Create {{slurm_log}} directory"
  ansible.builtin.file:
    path: "{{slurm_log}}"
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: "0755"
    state: directory

- name: 'slurm | install cgroup.conf'
  ansible.builtin.copy:
    src: cgroup.conf
    dest: "{{slurm_dir}}/cgroup.conf"
    mode: 0644
  notify:
    - 'restart munge service'
    - 'restart slurmd service'
    - 'restart slurmctld service'
  tags: cluster

- name: "slurm-client | Ensure slurmd is started"
  service:
    name: slurmd
    state: started
    enabled: true
  tags: cluster

- name: "cluster | Ensure slurmctld is started"
  service:
    name: slurmctld
    state: started
    enabled: true
  when:
    - "'head' in inventory_hostname"
    - ansible_facts['distribution'] == "Debian"
  tags: cluster
