---
galaxy_info:
  role_name: ntp
  author: franklin
  description: Configure ntp
  company: bitsmasher.net
  license: BSD
  min_ansible_version: 2.9
  platforms:
    - name: FreeBSD
      versions:
        - 13.0
    - name: OpenBSD
      versions:
        - 6.7
    - name: Ubuntu
      versions:
        - bionic
    - name: Devuan
      versions:
        - beowulf
  galaxy_tags: []
dependencies: []
collections:
  - community.general
