---
- name: "kerberize ssh client, authenticate"
  lineinfile:
    dest: /etc/ssh/ssh_config
    line: "GSSAPIAuthentication yes"
    insertafter: "#   GSSAPIAuthentication no"

- name: "kerberize ssh client, keyex"
  lineinfile:
    dest: /etc/ssh/ssh_config
    line: "GSSAPIKeyExchange yes"
    insertafter: "#   GSSAPIKeyExchange no"

- name: "kerberize ssh client, delegate credentials"
  lineinfile:
    dest: /etc/ssh/ssh_config
    line: "GSSAPITrustDNS yes"
    insertafter: "#   GSSAPITrustDNS no"
