version: '3'
services:
  mmmbot:
    image: mmmbot
    build:
      context: ..
      dockerfile: docker/Dockerfile.hanson
    container_name: hanson
    volumes:
      - ./src/hanson:/workspaces/hanson
