# syntax=docker/dockerfile:1

FROM python:3.9.1-slim-buster
LABEL maintainer "Franklin Diaz <franklin@bitsmasher.net>"
ENV DEBIAN_FRONTEND noninteractive

ADD . /app
WORKDIR /app

# env stuff
RUN apt update && apt -y install apt-utils
RUN make test
