FROM debian:buster
LABEL maintainer "Franklin Diaz <franklin@bitsmasher.net>"
ENV DEBIAN_FRONTEND noninteractive

ADD . /app
WORKDIR /app

# env stuff
RUN apt update && apt -y install apt-utils
RUN apt -y install python3-pip python3-setuptools; \
pip3 install -rpython/requirements-test.txt

#RUN apt -y install make git wget pandoc latexmk python3-pip \
#   python3-graphviz texlive-fonts-recommended texlive-latex-extra

# sphinx stuff
#RUN make python; \
#if [ ! -d "pygments-css" ]; then git clone https://github.com/richleland/pygments-css.git; fi; \
#cp ${WORKDIR}/pygments-css/vim.css ${WORKDIR}/docs/theme/static/
#RUN make docs
