version: '3'
services:
  franklin_resume:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: franklin_resume
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
  dev_franklin_resume:
    hostname: franklin_resume
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: dev_franklin_resume
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
