# syntax=docker/dockerfile:1

FROM golang:1.17.3-alpine3.13

LABEL maintainer="Franklin Diaz <fdiaz@paloaltonetworks.com>"
LABEL org.opencontainers.image.source="https://github.com/devsecfranklin/ps-devsecops-infra"

RUN apk add --virtual --no-cache \
  wget \
  unzip \
  bash \
  git \
  ca-certificates \
  openssh && rm -rf /var/cache/apk/*

