apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cloudbot-build-pod
  namespace: cloudbot
  labels:
    app: cloudbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudbot
  template:
    metadata:
      labels:
        app: cloudbot
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - dev-node 
      containers:
      - name: cloudbot
        image: gcr.io/gcp-gcs-pso/build-pod
