apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
  # Panorama Auth Key
  # request bootstrap vm-auth-key generate lifetime 8760
  PAN_PANORAMA_AUTH_KEY: "045934627370178"
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "a03b5dd2-d322-4a5e-8a82-68dd945213aa"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "41b0d74f61ca40fe9975dc71f0bc6fa8"
  #Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
