---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: "stat /etc/ntp.conf exists"
    stat:
      path: "/etc/ntp.conf"
    register: ntp_conf_stat

  - name: "check if /etc/ntp.conf exists"
    assert:
      that:
        - ntp_conf_stat.stat.exists == True
      success_msg: "/etc/ntp.conf exists"
      fail_msg: "/etc/ntp.conf doesn't exist"