[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = Colorado
L = Denver
O = franklin
OU = engr
CN = bitsmasher.net

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = head2
DNS.2 = head2.lab.bitsmasher.net
IP.1 = 10.10.12.19

