---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - token: "w2fjhc.e3ruhtv90grbr76d"
    description: "kubeadm bootstrap token"
    ttl: "24h"
cgroupDriver: systemd
nodeRegistration:
  name: head1.lab.bitsmasher.net
  criSocket: /var/run/dockershim.sock
  taints:
    - key: "kubeadmNode"
      value: "master"
      effect: "NoSchedule"
  imagePullPolicy: "IfNotPresent"
localAPIEndpoint:
  advertiseAddress: "10.10.12.18"
  bindPort: 6443
certificateKey: "e6a2eb8581237ab72a4f494f30285ec12a9694d750b9785706a83bfcbbbd2209"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.22.2
apiServer:
  extraArgs:
    anonymous-auth: "false"
    enable-admission-plugins: AlwaysPullImages,DefaultStorageClass
    audit-log-path: /var/log/cluster-audit.log
certificatesDir: /etc/kubernetes/pki
clusterName: tamarack
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
networking:
  dnsDomain: lab.bitsmasher.net
  podSubnet: 10.10.0.0/22
  serviceSubnet: 10.10.4.0/22
scheduler: {}
