---
- name: "Install Slurm scheduler on Raspi Cluster worker node"
  ansible.builtin.apt:
    package: ["slurmd", "slurm-client", "libpmix-dev"]
    state: latest
  tags: cluster

- name: 'install slurm.conf'
  ansible.builtin.copy:
    src: slurm.conf
    dest: /etc/slurm-llnl/slurm.conf
    mode: 0644
  tags: cluster

- name: 'install cgroup.conf for slurm worker'
  ansible.builtin.copy:
    src: cgroup.conf
    dest: /etc/slurm-llnl/cgroup.conf
    mode: 0644
  notify: "restart slurmd service"
  tags: cluster

- name: Change slurm file ownership, group and permissions
  ansible.builtin.file:
    path: /etc/slurm
    owner: slurm
    group: slurm
