---
- name: "ldap | Create /etc/ldap folder"
  ansible.builtin.file:
    path: "/etc/ldap"
    owner: "root"
    state: directory
    mode: 0755
  tags:
    - ldap

- name: "ldap | Add ldap.conf"
  ansible.builtin.template:
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    mode: 0644
  tags:
    - ldap

- name: 'Copy /etc/nsswitch.conf'
  ansible.builtin.copy:
    src: etc/nsswitch.conf
    dest: /etc/nsswitch.conf
    mode: 0644
  tags:
    - ldap

- name: "ldap | Copy /etc/libnss-ldap.conf"
  ansible.builtin.copy:
    src: etc/libnss-ldap.conf
    dest: /etc/libnss-ldap.conf
    mode: 0644
  tags:
    - ldap

- name: "ldap | Copy /etc/pam_ldap.conf"
  ansible.builtin.copy:
    src: etc/pam_ldap.conf
    dest: /etc/pam_ldap.conf
    mode: 0644
  tags:
    - ldap