---
- name: "Create /etc/ldap folder"
  ansible.builtin.file:
    path: "/etc/ldap"
    owner: "root"
    state: directory
    mode: 0755

- name: "Add ldap.conf"
  template:
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    mode: 0644

- name: 'Copy /etc/nsswitch.conf'
  ansible.builtin.copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    mode: 0644

- name: "Copy /etc/libnss-ldap.conf"
  ansible.builtin.copy:
    src: libnss-ldap.conf
    dest: /etc/libnss-ldap.conf
    mode: 0644

- name: "Copy /etc/pam_ldap.conf"
  ansible.builtin.copy:
    src: pam_ldap.conf
    dest: /etc/pam_ldap.conf
    mode: 0644

