---
- name: "Install packages"
  ansible.builtin.include_tasks: ldap_packages.yml

- name: "Install OpenLDAP"
  ansible.builtin.include_tasks: ldap_server.yml
  when: "'ldap' in ansible_hostname"

- name: "Install OpenLDAP Client"
  ansible.builtin.include_tasks: ldap_client.yml
