---
nfs_exports: [
    "/mnt/clusterfs 10.10.8.0/21(rw,sync,fsid=0,crossmnt,no_subtree_check,sec=krb5i)",
    "/mnt/clusterfs 10.0.0.0/24(rw,sync,no_subtree_check,sec=krb5i)",
    "/mnt/backup1 10.10.8.0/21(rw,sync,no_subtree_check)",
    "/mnt/backup1 10.0.0.0/24(rw,sync,no_subtree_check)"
    ]
snowy_nfs_exports: [
    "/mnt/storage1 10.10.8.0/21(rw,sync,no_subtree_check,root_squash)",
    "/mnt/storage1 10.0.0.0/24(rw,sync,no_subtree_check,root_squash)",
    "/opt/software 10.10.8.0/21(rw,sync,no_subtree_check,root_squash)",
    "/opt/software 10.0.0.0/24(rw,sync,no_subtree_check,root_squash)"
]
