---
- name: "Converge:: test nfs_client from lab.franklin Collection"
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: "Testing common"
      ansible.builtin.include_role:
        name: lab.franklin.common
        tasks_from: main.yml
