---
- name: "python | check if python3 is installed"
  ansible.builtin.command: which python3
  register: result

- name: "python | python3 status"
  ansible.builtin.debug:
    var: result.stdout

# - debug:
#     msg: |-
#       {% for i in _vars %}
#       {{ i }}:
#         {{ lookup('vars', i)|to_nice_yaml|indent(2) }}
#       {% endfor %}
