# version: '3' # docker-compose.yml: `version` is obsolete
services:
  customer-build:
    build:
      context: ..
      dockerfile: docker/rhel8/Dockerfile
      args:
        - RHEL_USER=$RHEL_USER
        - RHEL_PASS=$RHEL_PASS
    image: customer-build
    container_name: customer-build
    ports:
      - "5000:5000"
    volumes:
      - ./:/workspaces/customer-build
