apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-token
  namespace: hanson
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: "OTgxMjYyNzQ3OTAxNzgwMDI4.Gp3-hh.L4FHp3QxQuGVdNOWAqeZUgCkvr2hx7exL9ZmJc"
  DISCORD_BOT_GUILD: "867730185659088896"
  DISCORD_BOT_CHANNEL: "1009623414832648212"
  MASTODON_CLIENT_KEY: "Z4RwlfF_QXStA5MjMMaMtWfqFoOg6jrXwGRpcj0aYjc"
  MASTODON_CLIENT_SECRET: "2mf9nFdyYQmWkzj3cPxIBjpa4Zh1haZjSEGDFLaIqgM"
  MASTODON_ACCESS_TOKEN: "U9_6Ed0k9rsc5YNYTm7RxMYnrBvFraRY32_bvWguok8"
  GITHUB_TOKEN: "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"
  X_RAPID_API_KEY: "7a73d0b3b8msh0f68b5cd3ab862bp1789dfjsn4b41ee5d3672"