apiVersion: apps/v1
kind: DaemonSet
metadata: 
  labels:
    app: daemonset
  name: daemonset
spec:
  selector:
    matchLabels:
      app: daemonset
  template:
    metadata:
      labels:
        app: daemonset
    spec:
# This toleration would run daemon on master node as well
#        tolerations:
#        - key: node-role.kubernetes.io/master
#          effect: NoSchedule
      containers:
      - image: busybox 
        name: busybox
        args:
        - sleep
        - "100000"
