---
- name: "Install SSL packages"
  apt:
    package:
      [
        "python3-openssl",
        "libssl-dev",
        "openssl",
      ]
    state: latest
  tags: TLS

- name: "Install NTP packages"
  ansible.builtin.apt:
    name:
      - python3-openssl
      - libssl-dev
      - openssl
    force_apt_get: true
    update_cache: true
  tags:
    - TLS
    - LDAP
    - KRB5
  when:
  - ansible_facts['distribution'] == "Debian"

- name: 'Install certificate'
  ansible.builtin.include: ssl_client.yml

- name: "Copy in site CA cert"
  ansible.builtin.copy:
    src: ca.crt
    dest: "{{ cert }}"
    mode: 0444

- name: 'Copy cacert.pem in /etc/krb5'
  ansible.builtin.copy:
    src: ca.crt
    dest: /etc/krb5/cacert.pem
    mode: 0644
