---
- name: "codium | Make sure nmap is the latest version"
  community.general.openbsd_pkg:
    name: git
    state: latest

# ./scripts/build.sh
# ./scripts/package.sh
# doas pkg_add codium-*.tgz

- name: "codium | check build dir"
  ansible.builtin.stat:
    path: "{{build_dir}}"
  register: q

# clone the repo if it isn't there yet
- name: "codium | Clone the VSCodium repo"
  ansible.builtin.git:
    repo: https://github.com/VSCodium/vscodium.git
    dest: "{{software_dir}}"
  when:
    - q.stat.isdir is not defined

- name: "codium | build deps"
  ansible.builtin.command: "{{build_dir}}/scripts/install-build-deps.sh"
  args:
    chdir: "{{build_dir}}"

- name: "auks | configure "
  ansible.builtin.command: ./configure
  args:
    chdir: "{{auks_build_dir}}"

- name: "auks | Build the default AUKS target"
  community.general.make:
    chdir: "{{auks_build_dir}}"

- name: "auks | Make install AUKS"
  community.general.make:
    chdir: "{{auks_build_dir}}"
    target: install

- name: "auks | add /usr/local/lib to /etc/ld.so.conf"
  ansible.builtin.lineinfile:
    path: /etc/ld.so.conf
    line: "/usr/local/lib"
