---
- name: Restart exportfs
  command: exportfs -ra
  listen: "Restart exportfs"

- name: restart nfs-kernel-server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes
    daemon-reload: yes
  listen: "restart nfs-kernel-server"

- name: restart rpc-svcgssd
  ansible.builtin.service:
    name: rpc-svcgssd
    state: restarted
    enabled: yes
    daemon-reload: yes
  listen: "restart rpc-svcgssd"
