---
software_dir: /opt/software

auks_build_dir: "{{ software_dir }}/auks"
auks__packages_names:
  name:
    - git
    - flex
    - bison
    - byacc
    - autoconf
    - automake
    - zlib1g-dev

engr_user: franklin
engr_group: engr
engr_uid: 37
engr_gid: 9001

munge_user: munge
munge_group: munge

nhc_build_dir: "{{ software_dir }}/nhc"
nhc_log_dir: /var/log/nhc

slurm_dir: /etc/slurm-llnl
slurm_user: slurm
slurm_group: slurm
slurm_log: /var/log/slurm-llnl
