name: Cloud Run Deployment
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'fdiaz-gke-bot@gcp-gcs-pso.iam.gserviceaccount.com'
    - uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        image: 'ghcr.io/devsecfranklin/franklin-resume-amd64:latest'
        service: 'franklin-test'
