---
- name: 'kerberos | Install Kerberos Server Packages'
  ansible.builtin.apt:
    name:
      - krb5-kdc
      - krb5-admin-server
      - krb5-pkinit
      - krb5-kpropd
    force_apt_get: true
    update_cache: true
  tags:
    - Kerberos
    - auth
  when:
  - ansible_facts['distribution'] == "Debian"
