---
- name: "kerberos | Install Kerberos server packages"
  ansible.builtin.include_tasks: kerberos_server_packages.yml
  when:
    - "'server2' in ansible_hostname"
    - "'odroid-c1' in ansible_hostname"

- name: "kerberos | Install kerberos server setup"
  ansible.builtin.include_tasks: kerberos_server.yml
  when:
    - "'server2' in ansible_hostname"
    - "'odroid-c1' in ansible_hostname"

- name: "kerberos | Install Kerberos client packages"
  ansible.builtin.include_tasks: kerberos_client_packages.yml

- name: "kerberos | Init Kerberos client"
  ansible.builtin.include_tasks: configure.yml

- name: "kerberos | Configure Kerberos client"
  ansible.builtin.include_tasks: configure.yml

- name: "kerberos | Install Kerberos Client setup"
  ansible.builtin.include_tasks: kerberos_client.yml
