---
- name: "sssd | install sssd-krb5"
  apt:
    name:
      - sssd-krb5
      - sssd-ldap
      - sssd-tools     ##  sss_cache -U -G
    state: latest

- name: "sssd | provide identities from directory"
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
  #notify: restart sssd
  #when: kadmin.stat.exists
