---
my_private_key: /etc/ssl/private/server.pem
my_csr: /etc/ssl/server.csr
my_crt: /etc/ssl/certs/server.crt

key: /etc/ssl/private/server.key
cert: /etc/ssl/certs/lab.bitsmasher.net.crt

key_size: 4096
country_name: US
email_address: franklin@bitsmasher.net
organization_name: lab.bitsmasher.net

# lets encrypt
acme_challenge_type: http-01
acme_directory: https://acme-v02.api.letsencrypt.org/directory
acme_version: 2
acme_email: franklin@bitsmasher.net
letsencrypt_dir: /etc/letsencrypt
letsencrypt_keys_dir: /etc/letsencrypt/keys
letsencrypt_csrs_dir: /etc/letsencrypt/csrs
letsencrypt_certs_dir: /etc/letsencrypt/certs
letsencrypt_account_key: /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org
domain_name: bitsmasher.net
