apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  nodeSelector:
    env: dev-node
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do echo "Logging test! $i"; i=$((i+1)); sleep 1; done']
