apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp2
  name: webapp2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp2
    spec:
      containers:
      - image: nginx:1.17-alpine-perl
        name: nginx
        resources: {}
status: {}
