---
# - name: "Install timezone information"
#   ansible.builtin.package:
#     name: tzdata
#     state: present
#   when:
#   - ansible_facts['distribution'] == "Debian"

- name: "Install NTP packages"
  ansible.builtin.apt:
    name:
      - tzdata
      - systemd-timesyncd
    force_apt_get: true
    update_cache: true
  tags:
    - ntp
    - timezone
  when:
  - ansible_facts['distribution'] == "Debian"
