---
- name: "Install NTP packages"
  ansible.builtin.apt:
    name:
      - ntp
      - tzdata
      - systemd-timesyncd
    force_apt_get: true
    update_cache: true
  tags:
    - ntp
    - timezone
  when:
  - ansible_facts['distribution'] == "Debian"
