---
- name: Generate Private key
  openssl_privatekey: 
    path: "{{ my_private_key }}"

- name: Generate an OpenSSL Certificate Signing Request with Subject information
  openssl_csr:
    path: "{{ my_csr }}"
    privatekey_path: "{{ my_private_key }}"
    country_name: "{{ country_name }}"
    organization_name: "{{ organization_name }}"
    email_address: "{{ email_address }}"
    common_name: "{{ ansible_hostname }}"

- name: Generate an OpenSSL certificate signed with our CA certificate
  openssl_certificate:
    path: "{{ my_crt }}"
    csr_path: "{{ my_csr }}"
    ownca_path: "{{ cert }}" 
    ownca_privatekey_path: "{{ key }}"
    provider: ownca

- name: Check if a certificate is currently still valid, ignoring failures
  openssl_certificate:
    path: "{{ my_crt }}"
    provider: assertonly
    has_expired: False
  ignore_errors: True
  register: validity_check

- name: Ensure that the existing certificate belongs to the specified private key
  openssl_certificate:
    path: "{{ my_crt }}"
    privatekey_path: "{{ my_private_key }}"
    provider: assertonly