apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
 # Panorama Auth Key
  #PAN_PANORAMA_AUTH_KEY: "MDQ1OTM0NjI3MzcwMTc4"
  PAN_PANORAMA_AUTH_KEY: "447086375025616"
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "377acdc9-ed66-4273-9d03-704cd924eaf7"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "0aae28d8123446d892d2419560d6f9d5"
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
