apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: pa-cn
type: Opaque
stringData:
 # Panorama Auth Key
  #PAN_PANORAMA_AUTH_KEY: "MDQ1OTM0NjI3MzcwMTc4"
  PAN_PANORAMA_AUTH_KEY: "447086375025616"
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "e77280ac-4a72-4568-873e-b89bdf2fd439"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "d2070635aed04cf9b686bcae92cb6775"
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
