---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: franklin-resume-test
spec:
  taskRef:
    name: franklin-resume-test
  resources:
    inputs:
      - name: franklin-resume
        resourceRef:
          name: franklin-resume
