---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: python-project-template-test
spec:
  serviceAccountName: tekton-franklin-sa
  taskRef:
    name: python-project-template-test
  resources:
    inputs:
      - name: python-project-template
        resourceRef:
          name: python-project-template
