---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: terraform-aws-vmseries-modules-build-and-push
spec:
  serviceAccountName: cloud-bot
  taskRef:
    name: terraform-aws-vmseries-modules-build-and-push
  resources:
    inputs:
      - name: containerizer
        resourceRef:
          name: containerizer
