---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: terraform-panos-policy-test
spec:
  serviceAccountName: tekton-franklin-sa
  taskRef:
    name: terraform-panos-policy-test
  resources:
    inputs:
      - name: containerizer
        resourceRef:
          name: containerizer
      - name: terraform-panos-policy
        resourceRef:
          name: terraform-panos-policy
