galaxy_info:
  author: franklin
  company: your company (optional)
  role_name: nfs
  description: "Install and configure nfs on your system."
  license: MIT
  min_ansible_version: "2.14"
  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - nfs
    - system
