---
# this should be a soft link to /mnt/clusterfs/bin on the cluster
- name: "Create /home/franklin/bin"
  file:
    path: "/home/franklin/bin"
    owner: "franklin"
    state: link
    src: "{{ software_dir }}/bin"

- name: "Copy update_motd.sh script"
  copy:
    src: "{{ software_dir }}/git_cleanup.sh"
    dest: "{{ software_dir }}/bin/git_cleanup.sh"
    owner: "franklin"
    mode: 0755

# This is good for Debian hosts
# - name: "Update shell scripts on Debian"
#   ansible.builtin.include_tasks: debian_scripts.yml
#   when:
#   - ansible_facts['distribution'] == "Debian"
