---
- name: "Ansible Playbook for Raspi Servers"
  hosts: raspi_servers
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    isc_dhcp_scopes:
      - subnet: 10.10.8.0
        default_lease_time: "{{ isc_dhcp_default_lease_time }}"
        max_lease_time: "{{ isc_dhcp_max_lease_time }}"
        netmask: 255.255.248.0
        # Define scope specific options to configure
        options:
          - name: routers
            value: 10.10.8.1
          - name: subnet-mask
            value: 255.255.248.0
          - name: broadcast-address
            value: 10.10.15.255
          - name: domain-name-servers
            value: "{{ isc_dhcp_name_servers|join (', ') }}"
        range_start: 192.168.250.128
        range_end: 192.168.250.224
  roles:
    - python
    - security
    - ntp
    - common
    - dns
    - raspberrypi
    - ldap
    - kerberos
    - ssh
    - nfs
    - dhcp
    - shell
