name: Bandit Python Security Check
on:
  pull_request:
  push:
    branches:
      - main #dev, release, etc.
  release:
    types:
      - created

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 #get fuller history
      - name: Run Bandit
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: '--configfile .bandit -x .tox,docs,examples,_build,/src/inputs -s B101,B105,B108,B320,B410,B501'
