name: build - bio
on:
  - pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Compile biography
        uses: xu-cheng/latex-action@v4
        with:
          root_file: biography.tex
          args: '-xelatex -file-line-error -interaction=nonstopmode -synctex=1 -shell-escape biography'
          working_directory: biography