name: build container
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: build Debian bullseye container
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: |
          ./bootstrap.sh
          ./configure
          cd docker && make build
