# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE

on: [pull_request]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2.0.0

