name: Spell-Checker
on:
  push:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check spelling
      uses: check-spelling/check-spelling@0.0.17-alpha
