---
auks_build_dir: /tmp/auks
auks__packages_names:
  name:
    - git
    - flex
    - bison
    - byacc
    - autoconf
    - automake
    - zlib1g-dev
nhc_build_dir: /tmp/nhc

software_dir: /opt/software
engr_user: operator
engr_group: engr
engr_uid: 37
engr_gid: 9001
