---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab-franklin-cluster
  region: ca-central-1
  version: "1.24"

vpc:
  id: "vpc-07845540eeb2caac9"
  securityGroup: "sg-0850f8d381444abe7"


managedNodeGroups:
  - name: cn-series
    labels: { role: cn-series }
    instanceType: c4.large
    desiredCapacity: 10
    volumeSize: 80
    privateNetworking: true
