# SPDX-FileCopyrightText: 2023 DE:AD:10:C5 <franklin@dead10c5.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# dhcpd.conf
#
# Sample configuration file for ISC dhcpd
#

# option definitions common to all supported networks...
option domain-name "bitsmasher.net";
option domain-name-servers ns1.lab.bitsmasher.net, ns2.lab.bitsmasher.net;

default-lease-time 600;
max-lease-time 7200;

# The ddns-updates-style parameter controls whether or not the server will
# attempt to do a DNS update when a lease is confirmed. We default to the
# behavior of the version 2 packages ('none', since DHCP v2 didn't
# have support for DDNS.)
ddns-update-style none;

# If this DHCP server is the official DHCP server for the local
# network, the authoritative directive should be uncommented.
#authoritative;

# Use this to send dhcp log messages to a different log file (you also
# have to hack syslog.conf to complete the redirection).
#log-facility local7;

# A slightly different configuration for an internal subnet.
subnet 10.10.8.0 netmask 255.255.248.0 {
  range 10.10.14.0 10.10.14.127;
  option domain-name-servers ns1.lab.bitsmasher.net;
  option domain-name "lab.bitsmasher.net";
  option routers 10.10.8.1;
  option broadcast-address 10.10.15.255;
  default-lease-time 600;
  max-lease-time 7200;
  authoritative;
}

subnet 10.0.0.0 netmask 255.255.255.0 {
  not authoritative;
  ignore booting;
}

host node0 {
  hardware ethernet dc:a6:32:39:a4:7c;
  fixed-address 10.10.12.0;
}

host node1 {
  hardware ethernet dc:a6:32:39:88:e9;
  fixed-address 10.10.12.1;
}

host node2 {
  hardware ethernet dc:a6:32:39:a2:b1;
  fixed-address 10.10.12.2;
}

host node3 {
  hardware ethernet dc:a6:32:22:84:02;
  fixed-address 10.10.12.3;
}

# host node4 {
#   hardware ethernet dc:a6:32:22:84:02;
#   fixed-address 10.10.12.4;
# }

# host node5 {
#   hardware ethernet dc:a6:32:22:84:02;
#   fixed-address 10.10.12.5;
# }

# host node6 {
#   hardware ethernet dc:a6:32:22:84:02;
#   fixed-address 10.10.12.6;
# }

# host lanparty {
#   hardware ethernet 50:e5:49:c8:0d:4b;
#   fixed-address 10.10.12.7 ;
# }

host grimoire {
  hardware ethernet 00:e0:4c:68:05:41;
  fixed-address 10.10.12.8;
}

host labbench {
  hardware ethernet b8:27:eb:e5:ba:f1;
  fixed-address 10.10.12.11;
}

host server1 {
  hardware ethernet b8:27:eb:95:b2:6b;
  fixed-address 10.10.12.12;
}

host server2 {
  hardware ethernet b8:27:eb:ee:d2:09;
  fixed-address 10.10.12.13;
}

host storage1 {
  hardware ethernet dc:a6:32:a7:75:78;
  fixed-address 10.10.12.14;
}

host thelio {
  hardware ethernet 18:c0:4d:6d:31:92;
  fixed-address 10.10.12.17;
}

host head1 {
  hardware ethernet dc:a6:32:f9:9b:6f;
  fixed-address 10.10.12.18;
}

host head2 {
  hardware ethernet d8:3a:dd:d0:f2:50;
  fixed-address 10.10.12.19;
}

host media01 {
  hardware ethernet 00:0f:60:05:12:51;
  fixed-address 10.10.12.20;
}

host media02 {
  hardware ethernet b8:ca:3a:7d:23:f2;
  fixed-address 10.10.12.21;
}

host edge-t {
  hardware ethernet 28:bd:89:bc:63:9e;
  fixed-address 10.10.12.30;
}

host node900 {
  hardware ethernet 48:b0:2d:2e:83:98;
  fixed-address 10.10.12.90;
}

host node901 {
  hardware ethernet 48:b0:2d:2e:c1:44;
  fixed-address 10.10.12.91;
}

host node902 {
  hardware ethernet 48:b0:2d:2d:f2:95;
  fixed-address 10.10.12.92;
}

host node903 {
  hardware ethernet 48:b0:2d:2d:ee:48;
  fixed-address 10.10.12.93;
}

host odroid-c1 {
  hardware ethernet 00:1e:06:10:3d:76;
  fixed-address 10.10.12.254;
}

host server3 {
  hardware ethernet b8:27:eb:b1:c4:25;
  fixed-address 10.10.13.1;
}

host bbb1 {
  hardware ethernet 28:ec:9a:f1:26:d6;
  fixed-address 10.10.13.10;
}

host snowy {
  hardware ethernet 80:61:5f:11:ba:1d;
  fixed-address 10.10.8.11;
}

host netlab1 {
  hardware ethernet 00:03:ba:05:09:f1;
  fixed-address 10.10.8.3;
}

host netlab2 {
  hardware ethernet 00:03:ba:10:77:72;
  fixed-address 10.10.8.4
}

host blowfish {
  hardware ethernet 98:b7:85:21:ad:77;
  fixed-address 10.10.8.11;
}
